### ISSUE TITLE
performance data does not display correctly

### ISSUE THREAD

**Issue by p1kusmie** [NETWAYS/check_hp_ilo#1]
The output data is not displayed correctly.

![image](https://user-images.githubusercontent.com/47448475/162767948-068fccea-79bc-4b3c-bd8c-290e7e528a0a.png)

**Comment by p1kusmie** [comment]
#https://github.com/piotr3439/check_hp_ilo/commit/f96b14cd8cf4fdd0be662d1ec0438dc68e01264a

**Comment by lasag-2511** [comment]
device details and serial numbers doesnot print

**Comment by RincewindsHat** [comment]
Hi @ls440, could you elaborate on that problem? Ideally with more details, the steps you took to find the cause of the issue, the version of this software which are using and all of that in a new Issue please?

**Comment by lasag-2511** [comment]
Hi it’s not about performance data . I would like to get the device information for ex: 
ilo.get_product_name()
ProLiant BL460c Gen8
Created issue
