### ISSUE TITLE
get device info

### ISSUE THREAD

**Issue by lasag-2511** [NETWAYS/check_hp_ilo#3]
get the device information for ilo ex:
ilo.get_product_name()
ProLiant BL460c Gen8

**Comment by martialblog** [comment]
Hi, can you specify your requirements/feature request? Not sure what is meant here.

**Comment by lasag-2511** [comment]
Hi. Looking for something like this  which will print device information.  I would like to see the device information in the output.
 ex: "ProLiant BL460c Gen8"

     try:
         product_name = ilo.get_product_name()
    except:
         product_name = "Unknown HP Server"

**Comment by martialblog** [comment]
I don't have an ILO in front of the at the moment to test the in/output of the Plugin. But we can surely extend the functionality if you want to create a PR I'd be happy to review it.

**Comment by lasag-2511** [comment]
May be its good idea to define function ? But this doesnot work . May be we need to install other python library "proliantutils"

def product():

    try:
        ilo_client = hpilo.Ilo(args.ilo, args.user, args.password, port=args.port, timeout=args.timeout)
        product = ilo.client.get_product_name()
        return(f"\'{product}\'")
        print("product")
    except 
        product = "unknown HP"

**Comment by martialblog** [comment]
@ls440 Do you mean something like this? https://github.com/NETWAYS/check_hp_ilo/tree/feature/device-info

**Comment by lasag-2511** [comment]
yes right,  ilo.get_host_data() which displays both serial number of server and also product name, but i think we would need to grep this

**Comment by martialblog** [comment]
What's the current output? Shouldn't the `get_product_name()` function return only a string with the name?

**Comment by martialblog** [comment]
Just merged the code for the new Release. The output now looks like this:

```
[OK] Overall Status for (ProLiant BL460c Gen8)
 \ [OK] bios_hardware is OK
 \ [OK] fans is OK
 \ [OK] memory is OK
 \ [OK] network is OK
```

I decided to leave in the parenthesis since they could be used for `grep`
