### ISSUE TITLE
[Not Installed] battery - Critical alert

### ISSUE THREAD

**Issue by borisv1979** [NETWAYS/check_hp_ilo#4]
Hi,
we have a ProLiant server, which has no Smart Battery installed, so Overall status of hardware in your plugin is Critical. I tried to exclude 'battery', but it doesn't work. Any idea other than modify the code:

if status not in ["OK", "Redundant", **"Not Installed"**] or (args.exclude and check not in args.exclude):

**Comment by martialblog** [comment]
Without having the output in front of me, I would say that we could actually include the "Not Installed" into the list.

I thing it' reasonable to assume that not installed things are irrelevant for the check. 

Does is work as expected when you change it to `if status not in ["OK", "Redundant", "Not Installed"]` ?

**Comment by borisv1979** [comment]
Yes. When I change the code as I suggested, it works fine. As you said, "Not Installed" would be reasonable to include in your code, becouse those kind of HW state is practically normal ;)

**Comment by martialblog** [comment]
We just updated the Plugin
